// import { Geist, Geist_Mono } from "next/font/google";
import { poppins } from "@/app/ui/fonts/fonts";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "NDMS-A Tech way to maintain dues",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>{children}</body>
      {/* <body className="antialiased">{children}</body> */}
    </html>
  );
}
